<?php

use Illuminate\Database\Seeder;
use App\Campaign\Domain\Models\Area;
use App\Campaign\Domain\Models\Issue;
use App\Campaign\Domain\Models\Group;
use App\Missive\Domain\Models\Contact;
use App\Campaign\Domain\Models\Category;

class LagunaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $area_nodes = [
            'LAGUNA.CABUYAO.SALA.CAB-1',
            'LAGUNA.CABUYAO.SALA.CAB-2',
            'LAGUNA.CABUYAO.SALA.CAB-3',
            'LAGUNA.CABUYAO.SALA.CAB-4',
            'LAGUNA.CABUYAO.SALA.CAB-5',
            'LAGUNA.CABUYAO.SALA.CAB-6',
            'LAGUNA.CABUYAO.SALA.CAB-7',
            'LAGUNA.CABUYAO.SALA.CAB-8',
            'LAGUNA.CABUYAO.SALA.CAB-9',
            'LAGUNA.CABUYAO.SALA.CAB-10',
            'LAGUNA.CABUYAO.SALA.CAB-11',
            'LAGUNA.CABUYAO.BACLARAN.CAB-12',
            'LAGUNA.CABUYAO.BACLARAN.CAB-13',
            'LAGUNA.CABUYAO.BACLARAN.CAB-14',
            'LAGUNA.CABUYAO.BACLARAN.CAB-15',
            'LAGUNA.CABUYAO.BACLARAN.CAB-16',
            'LAGUNA.CABUYAO.BACLARAN.CAB-17',
            'LAGUNA.CABUYAO.BACLARAN.CAB-18',
            'LAGUNA.CABUYAO.BACLARAN.CAB-19',
            'LAGUNA.CABUYAO.BACLARAN.CAB-20',
            'LAGUNA.CABUYAO.BACLARAN.CAB-21',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-22',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-23',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-24',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-25',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-26',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-27',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-28',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-29',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-30',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-31',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-32',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-33',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-34',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-35',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-36',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-37',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-38',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-39',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-40',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-41',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-42',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-43',
            'LAGUNA.CABUYAO.BANAYBANAY.CAB-44',
            'LAGUNA.CABUYAO.BANLIC.CAB-45',
            'LAGUNA.CABUYAO.BANLIC.CAB-46',
            'LAGUNA.CABUYAO.BANLIC.CAB-47',
            'LAGUNA.CABUYAO.BANLIC.CAB-48',
            'LAGUNA.CABUYAO.BANLIC.CAB-49',
            'LAGUNA.CABUYAO.BANLIC.CAB-50',
            'LAGUNA.CABUYAO.BANLIC.CAB-51',
            'LAGUNA.CABUYAO.BANLIC.CAB-52',
            'LAGUNA.CABUYAO.BANLIC.CAB-53',
            'LAGUNA.CABUYAO.BANLIC.CAB-54',
            'LAGUNA.CABUYAO.BANLIC.CAB-55',
            'LAGUNA.CABUYAO.BANLIC.CAB-56',
            'LAGUNA.CABUYAO.BIGAA.CAB-57',
            'LAGUNA.CABUYAO.BIGAA.CAB-58',
            'LAGUNA.CABUYAO.BIGAA.CAB-59',
            'LAGUNA.CABUYAO.BIGAA.CAB-60',
            'LAGUNA.CABUYAO.BIGAA.CAB-61',
            'LAGUNA.CABUYAO.BIGAA.CAB-62',
            'LAGUNA.CABUYAO.BIGAA.CAB-63',
            'LAGUNA.CABUYAO.BIGAA.CAB-64',
            'LAGUNA.CABUYAO.BUTONG.CAB-65',
            'LAGUNA.CABUYAO.BUTONG.CAB-66',
            'LAGUNA.CABUYAO.BUTONG.CAB-67',
            'LAGUNA.CABUYAO.BUTONG.CAB-68',
            'LAGUNA.CABUYAO.BUTONG.CAB-69',
            'LAGUNA.CABUYAO.BUTONG.CAB-70',
            'LAGUNA.CABUYAO.BUTONG.CAB-71',
            'LAGUNA.CABUYAO.BUTONG.CAB-72',
            'LAGUNA.CABUYAO.BUTONG.CAB-73',
            'LAGUNA.CABUYAO.BUTONG.CAB-74',
            'LAGUNA.CABUYAO.CASILE.CAB-75',
            'LAGUNA.CABUYAO.CASILE.CAB-76',
            'LAGUNA.CABUYAO.DIEZMO.CAB-77',
            'LAGUNA.CABUYAO.DIEZMO.CAB-78',
            'LAGUNA.CABUYAO.DIEZMO.CAB-79',
            'LAGUNA.CABUYAO.DIEZMO.CAB-80',
            'LAGUNA.CABUYAO.GULOD.CAB-81',
            'LAGUNA.CABUYAO.GULOD.CAB-82',
            'LAGUNA.CABUYAO.GULOD.CAB-83',
            'LAGUNA.CABUYAO.GULOD.CAB-84',
            'LAGUNA.CABUYAO.GULOD.CAB-85',
            'LAGUNA.CABUYAO.GULOD.CAB-86',
            'LAGUNA.CABUYAO.GULOD.CAB-87',
            'LAGUNA.CABUYAO.GULOD.CAB-88',
            'LAGUNA.CABUYAO.GULOD.CAB-89',
            'LAGUNA.CABUYAO.GULOD.CAB-90',
            'LAGUNA.CABUYAO.MAMATID.CAB-91',
            'LAGUNA.CABUYAO.MAMATID.CAB-92',
            'LAGUNA.CABUYAO.MAMATID.CAB-93',
            'LAGUNA.CABUYAO.MAMATID.CAB-94',
            'LAGUNA.CABUYAO.MAMATID.CAB-95',
            'LAGUNA.CABUYAO.MAMATID.CAB-96',
            'LAGUNA.CABUYAO.MAMATID.CAB-97',
            'LAGUNA.CABUYAO.MAMATID.CAB-98',
            'LAGUNA.CABUYAO.MAMATID.CAB-99',
            'LAGUNA.CABUYAO.MAMATID.CAB-100',
            'LAGUNA.CABUYAO.MAMATID.CAB-101',
            'LAGUNA.CABUYAO.MAMATID.CAB-102',
            'LAGUNA.CABUYAO.MAMATID.CAB-103',
            'LAGUNA.CABUYAO.MAMATID.CAB-104',
            'LAGUNA.CABUYAO.MAMATID.CAB-105',
            'LAGUNA.CABUYAO.MAMATID.CAB-106',
            'LAGUNA.CABUYAO.MAMATID.CAB-107',
            'LAGUNA.CABUYAO.MAMATID.CAB-108',
            'LAGUNA.CABUYAO.MAMATID.CAB-109',
            'LAGUNA.CABUYAO.MAMATID.CAB-110',
            'LAGUNA.CABUYAO.MAMATID.CAB-111',
            'LAGUNA.CABUYAO.MAMATID.CAB-112',
            'LAGUNA.CABUYAO.MAMATID.CAB-113',
            'LAGUNA.CABUYAO.MAMATID.CAB-114',
            'LAGUNA.CABUYAO.MAMATID.CAB-115',
            'LAGUNA.CABUYAO.MAMATID.CAB-116',
            'LAGUNA.CABUYAO.MAMATID.CAB-117',
            'LAGUNA.CABUYAO.MAMATID.CAB-118',
            'LAGUNA.CABUYAO.MAMATID.CAB-119',
            'LAGUNA.CABUYAO.MAMATID.CAB-120',
            'LAGUNA.CABUYAO.MAMATID.CAB-121',
            'LAGUNA.CABUYAO.MAMATID.CAB-122',
            'LAGUNA.CABUYAO.MAMATID.CAB-123',
            'LAGUNA.CABUYAO.MAMATID.CAB-124',
            'LAGUNA.CABUYAO.MAMATID.CAB-125',
            'LAGUNA.CABUYAO.MARINIG.CAB-126',
            'LAGUNA.CABUYAO.MARINIG.CAB-127',
            'LAGUNA.CABUYAO.MARINIG.CAB-128',
            'LAGUNA.CABUYAO.MARINIG.CAB-129',
            'LAGUNA.CABUYAO.MARINIG.CAB-130',
            'LAGUNA.CABUYAO.MARINIG.CAB-131',
            'LAGUNA.CABUYAO.MARINIG.CAB-132',
            'LAGUNA.CABUYAO.MARINIG.CAB-133',
            'LAGUNA.CABUYAO.MARINIG.CAB-134',
            'LAGUNA.CABUYAO.MARINIG.CAB-135',
            'LAGUNA.CABUYAO.MARINIG.CAB-136',
            'LAGUNA.CABUYAO.MARINIG.CAB-137',
            'LAGUNA.CABUYAO.MARINIG.CAB-138',
            'LAGUNA.CABUYAO.MARINIG.CAB-139',
            'LAGUNA.CABUYAO.MARINIG.CAB-140',
            'LAGUNA.CABUYAO.MARINIG.CAB-141',
            'LAGUNA.CABUYAO.MARINIG.CAB-142',
            'LAGUNA.CABUYAO.MARINIG.CAB-143',
            'LAGUNA.CABUYAO.MARINIG.CAB-144',
            'LAGUNA.CABUYAO.MARINIG.CAB-145',
            'LAGUNA.CABUYAO.MARINIG.CAB-146',
            'LAGUNA.CABUYAO.MARINIG.CAB-147',
            'LAGUNA.CABUYAO.MARINIG.CAB-148',
            'LAGUNA.CABUYAO.MARINIG.CAB-149',
            'LAGUNA.CABUYAO.MARINIG.CAB-150',
            'LAGUNA.CABUYAO.MARINIG.CAB-151',
            'LAGUNA.CABUYAO.NIUGAN.CAB-152',
            'LAGUNA.CABUYAO.NIUGAN.CAB-153',
            'LAGUNA.CABUYAO.NIUGAN.CAB-154',
            'LAGUNA.CABUYAO.NIUGAN.CAB-155',
            'LAGUNA.CABUYAO.NIUGAN.CAB-156',
            'LAGUNA.CABUYAO.NIUGAN.CAB-157',
            'LAGUNA.CABUYAO.NIUGAN.CAB-158',
            'LAGUNA.CABUYAO.NIUGAN.CAB-159',
            'LAGUNA.CABUYAO.NIUGAN.CAB-160',
            'LAGUNA.CABUYAO.NIUGAN.CAB-161',
            'LAGUNA.CABUYAO.NIUGAN.CAB-162',
            'LAGUNA.CABUYAO.NIUGAN.CAB-163',
            'LAGUNA.CABUYAO.NIUGAN.CAB-164',
            'LAGUNA.CABUYAO.NIUGAN.CAB-165',
            'LAGUNA.CABUYAO.NIUGAN.CAB-166',
            'LAGUNA.CABUYAO.NIUGAN.CAB-167',
            'LAGUNA.CABUYAO.NIUGAN.CAB-168',
            'LAGUNA.CABUYAO.NIUGAN.CAB-169',
            'LAGUNA.CABUYAO.NIUGAN.CAB-170',
            'LAGUNA.CABUYAO.NIUGAN.CAB-171',
            'LAGUNA.CABUYAO.NIUGAN.CAB-172',
            'LAGUNA.CABUYAO.NIUGAN.CAB-173',
            'LAGUNA.CABUYAO.NIUGAN.CAB-174',
            'LAGUNA.CABUYAO.NIUGAN.CAB-175',
            'LAGUNA.CABUYAO.PITTLAND.CAB-176',
            'LAGUNA.CABUYAO.PITTLAND.CAB-177',
            'LAGUNA.CABUYAO.PITTLAND.CAB-178',
            'LAGUNA.CABUYAO.BARANGAY UNO.CAB-179',
            'LAGUNA.CABUYAO.BARANGAY UNO.CAB-180',
            'LAGUNA.CABUYAO.BARANGAY UNO.CAB-181',
            'LAGUNA.CABUYAO.BARANGAY UNO.CAB-182',
            'LAGUNA.CABUYAO.BARANGAY DOS.CAB-183',
            'LAGUNA.CABUYAO.BARANGAY DOS.CAB-184',
            'LAGUNA.CABUYAO.BARANGAY DOS.CAB-185',
            'LAGUNA.CABUYAO.BARANGAY TRES.CAB-186',
            'LAGUNA.CABUYAO.BARANGAY TRES.CAB-187',
            'LAGUNA.CABUYAO.BARANGAY TRES.CAB-188',
            'LAGUNA.CABUYAO.BARANGAY TRES.CAB-189',
            'LAGUNA.CABUYAO.PULO.CAB-190',
            'LAGUNA.CABUYAO.PULO.CAB-191',
            'LAGUNA.CABUYAO.PULO.CAB-192',
            'LAGUNA.CABUYAO.PULO.CAB-193',
            'LAGUNA.CABUYAO.PULO.CAB-194',
            'LAGUNA.CABUYAO.PULO.CAB-195',
            'LAGUNA.CABUYAO.PULO.CAB-196',
            'LAGUNA.CABUYAO.PULO.CAB-197',
            'LAGUNA.CABUYAO.PULO.CAB-198',
            'LAGUNA.CABUYAO.PULO.CAB-199',
            'LAGUNA.CABUYAO.PULO.CAB-200',
            'LAGUNA.CABUYAO.PULO.CAB-201',
            'LAGUNA.CABUYAO.PULO.CAB-202',
            'LAGUNA.CABUYAO.PULO.CAB-203',
            'LAGUNA.CABUYAO.PULO.CAB-204',
            'LAGUNA.CABUYAO.PULO.CAB-205',
            'LAGUNA.CABUYAO.PULO.CAB-206',
            'LAGUNA.CABUYAO.PULO.CAB-207',
            'LAGUNA.CABUYAO.PULO.CAB-208',
            'LAGUNA.CABUYAO.PULO.CAB-209',
            'LAGUNA.CABUYAO.PULO.CAB-210',
            'LAGUNA.CABUYAO.SAN ISIDRO.CAB-211',
            'LAGUNA.CABUYAO.SAN ISIDRO.CAB-212',
            'LAGUNA.CABUYAO.SAN ISIDRO.CAB-213',
            'LAGUNA.CABUYAO.SAN ISIDRO.CAB-214',
            'LAGUNA.CABUYAO.SAN ISIDRO.CAB-215',
            'LAGUNA.CABUYAO.SAN ISIDRO.CAB-216',
            'LAGUNA.CABUYAO.SAN ISIDRO.CAB-217',
            'LAGUNA.CABUYAO.SAN ISIDRO.CAB-218',
            'LAGUNA.CABUYAO.SAN ISIDRO.CAB-219',
            'LAGUNA.CABUYAO.SAN ISIDRO.CAB-220',
            'LAGUNA.CABUYAO.SAN ISIDRO.CAB-221',
            'LAGUNA.CABUYAO.SAN ISIDRO.CAB-222',
            'LAGUNA.CABUYAO.SAN ISIDRO.CAB-223',
            'LAGUNA.CABUYAO.SAN ISIDRO.CAB-224',
            'LAGUNA.CABUYAO.SAN ISIDRO.CAB-225',
            'LAGUNA.CABUYAO.SAN ISIDRO.CAB-226',
            'LAGUNA.LOS BANOS.BAYBAYIN.LB-1',
            'LAGUNA.LOS BANOS.BAYBAYIN.LB-2',
            'LAGUNA.LOS BANOS.MALINTA.LB-3',
            'LAGUNA.LOS BANOS.MALINTA.LB-4',
            'LAGUNA.LOS BANOS.MALINTA.LB-5',
            'LAGUNA.LOS BANOS.MALINTA.LB-6',
            'LAGUNA.LOS BANOS.MALINTA.LB-7',
            'LAGUNA.LOS BANOS.ANOS.LB-8',
            'LAGUNA.LOS BANOS.ANOS.LB-9',
            'LAGUNA.LOS BANOS.ANOS.LB-10',
            'LAGUNA.LOS BANOS.ANOS.LB-11',
            'LAGUNA.LOS BANOS.ANOS.LB-12',
            'LAGUNA.LOS BANOS.MAYONDON.LB-13',
            'LAGUNA.LOS BANOS.MAYONDON.LB-14',
            'LAGUNA.LOS BANOS.MAYONDON.LB-15',
            'LAGUNA.LOS BANOS.MAYONDON.LB-16',
            'LAGUNA.LOS BANOS.MAYONDON.LB-17',
            'LAGUNA.LOS BANOS.MAYONDON.LB-18',
            'LAGUNA.LOS BANOS.MAYONDON.LB-19',
            'LAGUNA.LOS BANOS.MAYONDON.LB-20',
            'LAGUNA.LOS BANOS.MAYONDON.LB-21',
            'LAGUNA.LOS BANOS.MAYONDON.LB-22',
            'LAGUNA.LOS BANOS.MAYONDON.LB-23',
            'LAGUNA.LOS BANOS.BAYOG.LB-24',
            'LAGUNA.LOS BANOS.BAYOG.LB-25',
            'LAGUNA.LOS BANOS.BAYOG.LB-26',
            'LAGUNA.LOS BANOS.BAYOG.LB-27',
            'LAGUNA.LOS BANOS.BAYOG.LB-28',
            'LAGUNA.LOS BANOS.BAYOG.LB-29',
            'LAGUNA.LOS BANOS.BAYOG.LB-30',
            'LAGUNA.LOS BANOS.SAN ANTONIO.LB-31',
            'LAGUNA.LOS BANOS.SAN ANTONIO.LB-32',
            'LAGUNA.LOS BANOS.SAN ANTONIO.LB-33',
            'LAGUNA.LOS BANOS.SAN ANTONIO.LB-34',
            'LAGUNA.LOS BANOS.SAN ANTONIO.LB-35',
            'LAGUNA.LOS BANOS.SAN ANTONIO.LB-36',
            'LAGUNA.LOS BANOS.SAN ANTONIO.LB-37',
            'LAGUNA.LOS BANOS.SAN ANTONIO.LB-38',
            'LAGUNA.LOS BANOS.MAAHAS.LB-39',
            'LAGUNA.LOS BANOS.MAAHAS.LB-40',
            'LAGUNA.LOS BANOS.MAAHAS.LB-41',
            'LAGUNA.LOS BANOS.MAAHAS.LB-42',
            'LAGUNA.LOS BANOS.MAAHAS.LB-43',
            'LAGUNA.LOS BANOS.PUTHO-TUNTUNGIN.LB-44',
            'LAGUNA.LOS BANOS.PUTHO-TUNTUNGIN.LB-45',
            'LAGUNA.LOS BANOS.PUTHO-TUNTUNGIN.LB-46',
            'LAGUNA.LOS BANOS.PUTHO-TUNTUNGIN.LB-47',
            'LAGUNA.LOS BANOS.PUTHO-TUNTUNGIN.LB-48',
            'LAGUNA.LOS BANOS.PUTHO-TUNTUNGIN.LB-49',
            'LAGUNA.LOS BANOS.BAGONG SILANG.LB-50',
            'LAGUNA.LOS BANOS.BATONG MALAKE.LB-51',
            'LAGUNA.LOS BANOS.BATONG MALAKE.LB-52',
            'LAGUNA.LOS BANOS.BATONG MALAKE.LB-53',
            'LAGUNA.LOS BANOS.BATONG MALAKE.LB-54',
            'LAGUNA.LOS BANOS.BATONG MALAKE.LB-55',
            'LAGUNA.LOS BANOS.BATONG MALAKE.LB-56',
            'LAGUNA.LOS BANOS.BATONG MALAKE.LB-57',
            'LAGUNA.LOS BANOS.BATONG MALAKE.LB-58',
            'LAGUNA.LOS BANOS.BATONG MALAKE.LB-59',
            'LAGUNA.LOS BANOS.TIMUGAN POB.LB-60',
            'LAGUNA.LOS BANOS.TIMUGAN POB.LB-61',
            'LAGUNA.LOS BANOS.TIMUGAN POB.LB-62',
            'LAGUNA.LOS BANOS.TIMUGAN POB.LB-63',
            'LAGUNA.LOS BANOS.LALAKAY.LB-64',
            'LAGUNA.LOS BANOS.LALAKAY.LB-65',
            'LAGUNA.LOS BANOS.LALAKAY.LB-66',
            'LAGUNA.LOS BANOS.LALAKAY.LB-67',
            'LAGUNA.LOS BANOS.LALAKAY.LB-68',
            'LAGUNA.LOS BANOS.LALAKAY.LB-69',
            'LAGUNA.LOS BANOS.LALAKAY.LB-70',
            'LAGUNA.LOS BANOS.BAMBANG.LB-71',
            'LAGUNA.LOS BANOS.BAMBANG.LB-72',
            'LAGUNA.LOS BANOS.BAMBANG.LB-73',
            'LAGUNA.LOS BANOS.BAMBANG.LB-74',
            'LAGUNA.LOS BANOS.BAMBANG.LB-75',
            'LAGUNA.BAY.SAN AGUSTIN.BAY-1',
            'LAGUNA.BAY.SAN AGUSTIN.BAY-2',
            'LAGUNA.BAY.SAN NICOLAS.BAY-3',
            'LAGUNA.BAY.SAN NICOLAS.BAY-4',
            'LAGUNA.BAY.SAN ISIDRO.BAY-5',
            'LAGUNA.BAY.SAN ISIDRO.BAY-6',
            'LAGUNA.BAY.DILA.BAY-7',
            'LAGUNA.BAY.DILA.BAY-8',
            'LAGUNA.BAY.DILA.BAY-9',
            'LAGUNA.BAY.DILA.BAY-10',
            'LAGUNA.BAY.TAGUMPAY.BAY-11',
            'LAGUNA.BAY.TAGUMPAY.BAY-12',
            'LAGUNA.BAY.SAN ANTONIO.BAY-13',
            'LAGUNA.BAY.SAN ANTONIO.BAY-14',
            'LAGUNA.BAY.SAN ANTONIO.BAY-15',
            'LAGUNA.BAY.SAN ANTONIO.BAY-16',
            'LAGUNA.BAY.CALO.BAY-17',
            'LAGUNA.BAY.CALO.BAY-18',
            'LAGUNA.BAY.CALO.BAY-19',
            'LAGUNA.BAY.MAITIM.BAY-20',
            'LAGUNA.BAY.MAITIM.BAY-21',
            'LAGUNA.BAY.MAITIM.BAY-22',
            'LAGUNA.BAY.SANTO DOMINGO.BAY-23',
            'LAGUNA.BAY.SANTO DOMINGO.BAY-24',
            'LAGUNA.BAY.SANTO DOMINGO.BAY-25',
            'LAGUNA.BAY.SANTO DOMINGO.BAY-26',
            'LAGUNA.BAY.SANTO DOMINGO.BAY-27',
            'LAGUNA.BAY.SANTO DOMINGO.BAY-28',
            'LAGUNA.BAY.PACIANO RIZAL.BAY-29',
            'LAGUNA.BAY.PACIANO RIZAL.BAY-30',
            'LAGUNA.BAY.PACIANO RIZAL.BAY-31',
            'LAGUNA.BAY.PUYPUY.BAY-32',
            'LAGUNA.BAY.PUYPUY.BAY-33',
            'LAGUNA.BAY.PUYPUY.BAY-34',
            'LAGUNA.BAY.MASAYA.BAY-35',
            'LAGUNA.BAY.MASAYA.BAY-36',
            'LAGUNA.BAY.MASAYA.BAY-37',
            'LAGUNA.BAY.MASAYA.BAY-38',
            'LAGUNA.BAY.TRANCA.BAY-39',
            'LAGUNA.BAY.TRANCA.BAY-40',
            'LAGUNA.BAY.TRANCA.BAY-41',
            'LAGUNA.BAY.SANTA CRUZ.BAY-42',
            'LAGUNA.BAY.SANTA CRUZ.BAY-43',
            'LAGUNA.BAY.BITIN.BAY-44',
            'LAGUNA.BAY.BITIN.BAY-45',
            'LAGUNA.BAY.BITIN.BAY-46',
            'LAGUNA.BAY.BITIN.BAY-47',
            'LAGUNA.BAY.BITIN.BAY-48',
        ];

        $group_nodes = [
            'HQ.CORE',
            'HQ.VOLUNTEER',
            'HQ.WATCHER',
            'HQ.VOTER',
        ];

        DB::transaction(function () use ($group_nodes, $area_nodes) {
            $contact = Contact::create(['mobile' => '+639954705290', 'handle' => 'HQ 1']);
            Contact::create(['mobile' => '+639202371976', 'handle' => 'HQ 2'], $contact);
            Contact::create(['mobile' => '+639565711304', 'handle' => 'HQ 3'], $contact);

            $category = Category::create(['name' => 'Governor']);
            Issue::make(['code' => 'RAMIL', 'name' => 'Ramil Hernandez'])->category()->associate($category)->save();
            Issue::make(['code' => 'ER', 'name' => 'ER Ejercito'])->category()->associate($category)->save();

            $category = Category::create(['name' => 'Representative']);
            Issue::make(['code' => 'BANJO', 'name' => 'Banjo Caringal'])->category()->associate($category)->save();
            Issue::make(['code' => 'GENUINO', 'name' => 'Efraim Genuino'])->category()->associate($category)->save();
            Issue::make(['code' => 'HEMEDEZ', 'name' => 'Isidro Hemedez Jr.'])->category()->associate($category)->save();
            Issue::make(['code' => 'RUTH', 'name' => 'Ruth Hernandez'])->category()->associate($category)->save();
            Issue::make(['code' => 'TIRSO', 'name' => 'Tirso Lavina'])->category()->associate($category)->save();
            Issue::make(['code' => 'REVILLA', 'name' => 'Rosauro Revilla'])->category()->associate($category)->save();

            $category = Category::create(['name' => 'System']);
            Issue::make(['code' => 'TOTAL', 'name' => 'Total Voters'])->category()->associate($category)->save();

            foreach ($area_nodes as $area_node) {
                Area::build($area_node);
            }

            foreach ($group_nodes as $group_node) {
                Group::build($group_node);
            }
        });
    }
}
